"" 1. Editing.

" internal encoding
set encoding=utf-8
" file encoding
" ucs-bom: read the bom if you've got it
" utf-8: the best encoding
" sjis: japanese
" gbk: simplified chinese
" big5: traditional chinese (this autodetect isn't working??)
" latin1: a printable fallback encoding
set fileencodings=ucs-bom,utf-8,sjis,gbk,big5,latin1

" ensure autodetection of proper colors and indentation
filetype plugin indent on
syntax enable
set autoindent
set modeline

" recognize file types
au BufRead,BufNewFile Snakefile set filetype=python
au BufRead,BufNewFile config.txt set filetype=config
au BufRead,BufNewFile *.cls set filetype=tex

au FileType gitconfig setlocal noexpandtab

" rainbow csv/tsv
" TODO: change "set number" to "setlocal number"
"       and push it upstream
let g:rcsv_colorpairs = [['NONE', 'NONE'], ['cyan', 'cyan'], ['red', 'red'], ['green', 'green'], ['magenta', 'magenta'], ['yellow', 'yellow'], ['blue', 'blue'], ['darkred', 'darkred'], ['darkgreen', 'darkgreen'], ['darkmagenta', 'darkmagenta']]
" TODO: push this autocmd upstream to rainbow-csv as well
autocmd FileType tsv setlocal noexpandtab
" disable hover: it causes problems on narrow displays
autocmd FileType tsv let g:disable_rainbow_hover = 1
autocmd FileType csv let g:disable_rainbow_hover = 1
" TODO: extend rainbowcsv's gitignore to ignore
"       autogenerated syntax files


" python-syntax
let python_highlight_all = 1

" move cursor where there are no characters
set virtualedit=all

" don't make tabs
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" scroll with mouse
set mouse+=a
if &term =~ '^screen'
    set ttymouse=xterm2
endif

" make long lines easier
function Wrapper()
    setlocal wrap
    setlocal linebreak
    nnoremap j gj
    nnoremap k gk
    nnoremap gj j
    nnoremap gk k
    vnoremap j gj
    vnoremap k gk
    vnoremap gj j
    vnoremap gk k
endfunction

function NoWrapper()
    setlocal nowrap
    setlocal nolinebreak
    nunmap j
    nunmap k
    nunmap gj
    nunmap gk
    vunmap j
    vunmap k
    vunmap gj
    vunmap gk
endfunction

command Wrap call Wrapper()
command Nowrap call NoWrapper()

Wrap

" fast escape
if ! has('gui_running')
    set ttimeoutlen=10
    augroup FastEscape
        autocmd!
        au InsertEnter * set timeoutlen=0
        au InsertLeave * set timeoutlen=1000
    augroup END
endif

" search-as-you-type in "/" searches
set incsearch

" highlight all search matches
" (hide current results with :noh)
set hlsearch

" split down and to the right, rather than left and above
set splitbelow
set splitright

" just stop with the ex mode
nnoremap Q <nop>

" indent when wrapping
" http://stackoverflow.com/questions/1204149/smart-wrap-in-vim
" and a way to disable it
" showbreak doesn't seem to actually be local
function Copyer()
    setlocal showbreak=
    setlocal nolinebreak
endfunction

function NoCopyer()
    setlocal showbreak=>>\ \ \ \ \ \ \ \ 
    setlocal linebreak
endfunction

command Copy call Copyer()
command Nocopy call NoCopyer()

Nocopy

" shorthand for prev/next buffer
nmap <C-P> :bp<CR>
nmap <C-N> :bn<CR>

" case insensitive filename completion
set wildignorecase

" F1 help is not helpful. Use F1 to enlarge Esc instead.
map <F1> <Esc>
imap <F1> <Esc>


"" 2. Display.

" show the command typed so far
set showcmd

" show statusline
set laststatus=2
" show where in the file we are
set ruler

" for fallback if inkpot fails since I use a dark terminal
set bg=dark

" Inkpot, a downloaded colorscheme
" (Inkpot is a 256-color dark color scheme. Among its virtues are good reds
" and greens for diff mode.)
colorscheme inkpot

" keep lines on screen after cursor
set so=2

" Cursor shape for terminals that support it, e.g. mintty
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

" stop beeping. you can visual beep
set visualbell


"" 3. Meta.

" source local vimrc, per http://blog.sanctum.geek.nz/local-vimrc-files/
if filereadable(glob("~/.vimrc.local")) 
    source ~/.vimrc.local
endif
